[constant]
# Do not change
Tc = 2.269

[ising]
# This section has parameters to quickly show the working of the Ising Model

    # random number seed
    random_number_seed = 450

    # small latice
    D = 20

    # temperature range
    initial_temp = 1.85
    final_temp = 3
    temp_steps = 20 

    # finite size scaling
    intial_lattice = 10
    final_lattice = 50
    lattice_step = 5

[experiment_1]
# This is similar to ising section with a different random number seed, 
# just to showcase the variability in the initial configuration

    # random number seed
    random_number_seed = 572

    # small latice
    D = 20

    # temperature range
    initial_temp = 1.85
    final_temp = 3
    temp_steps = 20 

    # finite size scaling
    intial_lattice = 10
    final_lattice = 50
    lattice_step = 5

[experiment_2]
# Here, the lattice size is increased which will increase the computation time

    random_number_seed = 450

    # medium lattice
    D = 50

    # temperature range
    initial_temp = 1.85
    final_temp = 3
    temp_steps = 20 

    # finite size scaling
    intial_lattice = 10
    final_lattice = 50
    lattice_step = 5


[experiment_3]
# Here, the lattice size is increased which will increase the computation time

    # random number seed
    random_number_seed = 450

    # large lattice
    D = 100

    # temperature range
    initial_temp = 1.85
    final_temp = 3
    temp_steps = 20 

    # finite size scaling
    intial_lattice = 10
    final_lattice = 50
    lattice_step = 5


